### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [uZetta27/EasyROP#1]
looks like a nice tool, congrats! 

just few comments:
- project has no description? it is "No description or website provided." now.
- will you have a README in English?

keep it up, cheers.

**Comment by cbOverhead** [comment]
There you go!

Thanks for bring us such an amazing tool

**Comment by aquynh** [comment]
great, we linked to your tool from our website now: http://www.capstone-engine.org/showcase.html

cheers.
